# -*- coding: utf-8 -*-
"""FindPhraseInSRT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HDRQ360mksvFRf7ZDSITd1t8kvgxapf
"""

def readTextFile(path):
  with open(path) as f:
    captions=f.readlines()
  return captions

file=readTextFile("/content/drive/MyDrive/suitSRT.txt")

print(file)

n=len(file)
print(n)

descriptions={}

first=0
second=1
third=2
n=len(file)
for line in file:
  if first==n-2:
    #print("A")
    break
  descriptions[file[first]]=file[second]
  print(first)
  first+=3
  second+=3
  third+=3

file[0]

descriptions

('Chef, what makes you\n')

for key,value in descriptions.items():
  descriptions[key]=(descriptions[key]).split()

print(descriptions)

word_to_find='backdating' # replace with the word u wanna search
for key,value in descriptions.items():
  current_list=descriptions.get(key)
  for word in current_list:
    if word==word_to_find:
      print(key)
      break

